[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kivycore"
version = "0.1.0"
description = "Core app and components for my Kivy project"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]